ubuntu@ip-172-31-17-208:~/DevOps_Microservices/project-ml-microservice-kubernetes$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "udacity-prediction" already exists
NAME                 READY   STATUS    RESTARTS   AGE
udacity-prediction   1/1     Running   0          110s
Forwarding from 127.0.0.1:8085 -> 80
Forwarding from [::1]:8085 -> 80
Handling connection for 8085
Handling connection for 8085

#inner output
ubuntu@ip-172-31-17-208:~/DevOps_Microservices/project-ml-microservice-kubernetes$ kubectl logs udacity-prediction
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 322-355-976
[2023-02-12 03:07:32,597] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-02-12 03:07:32,613] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-02-12 03:07:32,623] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-02-12 03:07:32,627] INFO in app: prediction: [20.35373177134412]
127.0.0.1 - - [12/Feb/2023 03:07:32] "POST /predict HTTP/1.1" 200 -